-- Stage 0C: leads table scaffold only.
-- Do not auto-apply in app startup; run manually in Supabase SQL editor/migrations workflow.

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text,
  email text,
  vehicle_interest text,
  notes text,
  source text,
  status text not null default 'new',
  created_at timestamptz not null default now()
);

comment on table public.leads is 'Stage 0C scaffold table for CRM leads.';
