-- Stage 4: lightweight append-only lead activity history.
-- Run manually in Supabase SQL editor/migrations workflow.

create table if not exists public.lead_activities (
  id bigint generated by default as identity primary key,
  lead_id bigint not null references public.leads(id) on delete cascade,
  type text not null,
  note text,
  created_at timestamptz not null default now()
);
