-- Stage 5: lightweight lead follow-up reminders.
-- Run manually in Supabase SQL editor/migrations workflow.

create table if not exists public.lead_reminders (
  id bigint generated by default as identity primary key,
  lead_id bigint not null references public.leads(id) on delete cascade,
  title text not null,
  note text,
  due_at timestamptz not null,
  completed boolean not null default false,
  created_at timestamptz not null default now()
);
