-- Communication Architecture Foundation: canonical lead communication timeline.
-- Run manually after 001-006 in the Supabase SQL editor/migrations workflow.

create table if not exists public.communication_events (
  id bigint generated by default as identity primary key,
  lead_id bigint not null references public.leads(id) on delete cascade,
  event_type text not null check (event_type in ('manual_note', 'status_change', 'reminder_created')),
  direction text not null default 'internal' check (direction in ('internal', 'inbound', 'outbound')),
  occurred_at timestamptz not null default now(),
  body text,
  metadata jsonb not null default '{}'::jsonb,
  created_source text not null
);

create index if not exists communication_events_lead_occurred_at_idx
  on public.communication_events (lead_id, occurred_at desc);

alter table public.communication_events enable row level security;

do $$
declare
  existing_policy record;
begin
  for existing_policy in
    select policyname
    from pg_policies
    where schemaname = 'public'
      and tablename = 'communication_events'
  loop
    execute format('drop policy if exists %I on public.communication_events', existing_policy.policyname);
  end loop;
end
$$;

insert into public.communication_events (lead_id, event_type, direction, occurred_at, body, metadata, created_source)
select
  activity.lead_id,
  'manual_note',
  'internal',
  activity.created_at,
  coalesce(activity.note, 'Logged ' || activity.type || ' activity'),
  jsonb_build_object('activity_id', activity.id, 'activity_type', activity.type),
  'lead_activity_backfill'
from public.lead_activities as activity
where not exists (
  select 1
  from public.communication_events as event
  where event.metadata->>'activity_id' = activity.id::text
);

insert into public.communication_events (lead_id, event_type, direction, occurred_at, body, metadata, created_source)
select
  reminder.lead_id,
  'reminder_created',
  'internal',
  reminder.created_at,
  coalesce(reminder.note, reminder.title),
  jsonb_build_object('reminder_id', reminder.id, 'title', reminder.title, 'due_at', reminder.due_at),
  'lead_reminder_backfill'
from public.lead_reminders as reminder
where not exists (
  select 1
  from public.communication_events as event
  where event.metadata->>'reminder_id' = reminder.id::text
);

insert into public.communication_events (lead_id, event_type, direction, occurred_at, body, metadata, created_source)
select
  lead.id,
  'manual_note',
  'internal',
  lead.created_at,
  lead.notes,
  jsonb_build_object('lead_id', lead.id),
  'lead_note_backfill'
from public.leads as lead
where lead.notes is not null
  and btrim(lead.notes) <> ''
  and not exists (
    select 1
    from public.communication_events as event
    where event.created_source = 'lead_note_backfill'
      and event.metadata->>'lead_id' = lead.id::text
  );

insert into public.communication_events (lead_id, event_type, direction, occurred_at, body, metadata, created_source)
select
  lead.id,
  'status_change',
  'internal',
  lead.updated_at,
  'Current status: ' || lead.status,
  jsonb_build_object('lead_id', lead.id, 'status', lead.status),
  'lead_status_snapshot'
from public.leads as lead
where not exists (
  select 1
  from public.communication_events as event
  where event.created_source = 'lead_status_snapshot'
    and event.metadata->>'lead_id' = lead.id::text
);

create or replace function public.record_lead_activity_communication_event()
returns trigger
language plpgsql
as $$
begin
  insert into public.communication_events (lead_id, event_type, direction, occurred_at, body, metadata, created_source)
  values (
    new.lead_id,
    'manual_note',
    'internal',
    new.created_at,
    coalesce(new.note, 'Logged ' || new.type || ' activity'),
    jsonb_build_object('activity_id', new.id, 'activity_type', new.type),
    'lead_activity'
  );
  return new;
end;
$$;

create or replace function public.record_lead_reminder_communication_event()
returns trigger
language plpgsql
as $$
begin
  insert into public.communication_events (lead_id, event_type, direction, occurred_at, body, metadata, created_source)
  values (
    new.lead_id,
    'reminder_created',
    'internal',
    new.created_at,
    coalesce(new.note, new.title),
    jsonb_build_object('reminder_id', new.id, 'title', new.title, 'due_at', new.due_at),
    'lead_reminder'
  );
  return new;
end;
$$;

create or replace function public.record_lead_status_communication_event()
returns trigger
language plpgsql
as $$
begin
  insert into public.communication_events (lead_id, event_type, direction, occurred_at, body, metadata, created_source)
  values (
    new.id,
    'status_change',
    'internal',
    new.updated_at,
    'Status changed from ' || old.status || ' to ' || new.status,
    jsonb_build_object('previous_status', old.status, 'status', new.status),
    'lead_status_update'
  );
  return new;
end;
$$;

drop trigger if exists lead_activities_record_communication_event on public.lead_activities;
create trigger lead_activities_record_communication_event
after insert on public.lead_activities
for each row execute function public.record_lead_activity_communication_event();

drop trigger if exists lead_reminders_record_communication_event on public.lead_reminders;
create trigger lead_reminders_record_communication_event
after insert on public.lead_reminders
for each row execute function public.record_lead_reminder_communication_event();

drop trigger if exists leads_record_status_communication_event on public.leads;
create trigger leads_record_status_communication_event
after update of status on public.leads
for each row
when (old.status is distinct from new.status)
execute function public.record_lead_status_communication_event();
