-- Conversation State Foundation: minimal lead conversation identity/state.
-- Run manually after 008 in the Supabase SQL editor/migrations workflow.

create table if not exists public.conversations (
  id bigint generated by default as identity primary key,
  lead_id bigint not null references public.leads(id) on delete cascade,
  channel_type text not null check (channel_type in ('sms')),
  status text not null default 'active' check (status in ('active', 'closed')),
  last_activity_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists conversations_lead_channel_status_idx
  on public.conversations (lead_id, channel_type, status);

create unique index if not exists conversations_one_active_sms_per_lead_idx
  on public.conversations (lead_id)
  where channel_type = 'sms' and status = 'active';

alter table public.conversations enable row level security;

do $$
declare
  existing_policy record;
begin
  for existing_policy in
    select policyname
    from pg_policies
    where schemaname = 'public'
      and tablename = 'conversations'
  loop
    execute format('drop policy if exists %I on public.conversations', existing_policy.policyname);
  end loop;
end
$$;

alter table public.communication_events
  add column if not exists conversation_id bigint references public.conversations(id) on delete set null;

create index if not exists communication_events_conversation_occurred_at_idx
  on public.communication_events (conversation_id, occurred_at desc);

insert into public.conversations (lead_id, channel_type, status, last_activity_at, created_at, updated_at)
select
  event.lead_id,
  'sms',
  'active',
  max(event.occurred_at),
  min(event.occurred_at),
  max(event.occurred_at)
from public.communication_events as event
where event.event_type = 'outbound_sms'
group by event.lead_id
on conflict do nothing;

update public.communication_events as event
set conversation_id = conversation.id
from public.conversations as conversation
where event.event_type = 'outbound_sms'
  and event.conversation_id is null
  and conversation.lead_id = event.lead_id
  and conversation.channel_type = 'sms'
  and conversation.status = 'active';

create or replace function public.record_outbound_sms_communication_event(
  p_lead_id bigint,
  p_occurred_at timestamptz,
  p_body text,
  p_twilio_message_sid text,
  p_twilio_status text
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  active_conversation_id bigint;
  inserted_event_id bigint;
begin
  select id
  into active_conversation_id
  from public.conversations
  where lead_id = p_lead_id
    and channel_type = 'sms'
    and status = 'active'
  order by updated_at desc
  limit 1;

  if active_conversation_id is null then
    insert into public.conversations (lead_id, channel_type, status, last_activity_at)
    values (p_lead_id, 'sms', 'active', p_occurred_at)
    returning id into active_conversation_id;
  end if;

  insert into public.communication_events (
    lead_id,
    conversation_id,
    event_type,
    direction,
    occurred_at,
    body,
    metadata,
    created_source
  )
  values (
    p_lead_id,
    active_conversation_id,
    'outbound_sms',
    'outbound',
    p_occurred_at,
    p_body,
    jsonb_build_object('twilio_message_sid', p_twilio_message_sid, 'twilio_status', p_twilio_status),
    'twilio_outbound_sms'
  )
  returning id into inserted_event_id;

  update public.conversations
  set
    last_activity_at = greatest(coalesce(last_activity_at, p_occurred_at), p_occurred_at),
    updated_at = now()
  where id = active_conversation_id;

  return inserted_event_id;
end;
$$;

revoke execute on function public.record_outbound_sms_communication_event(bigint, timestamptz, text, text, text) from public, anon, authenticated;
grant execute on function public.record_outbound_sms_communication_event(bigint, timestamptz, text, text, text) to service_role;
